/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.workoutmenugeneratorapp;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author eitanaka
 */
public class DailyMenuWindow extends javax.swing.JFrame {    
    
    private WeeklyMenuWindow weeklyMenuWin;    
    private LogInWindow logInWin;
    private UserInformationWindow userInfoWin;
    
    private ArrayList<ArrayList<WorkoutMenuItem>> weeklyMenu;
            
    /**
     * Creates new form DailyMenuWindow
     */
    public DailyMenuWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        dailyMenuLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dailyMenuList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionField = new javax.swing.JTextArea();
        instructionLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        menuDetailBtn = new javax.swing.JButton();
        weeklyBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        repsLabel = new javax.swing.JLabel();
        repsField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Menu");

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        titleLabel.setText("Workout Generator");

        dailyMenuLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dailyMenuLabel.setText("Today's Menu:");

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name:");

        dailyMenuList.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        dailyMenuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dailyMenuList);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instruction:");

        instructionField.setColumns(20);
        instructionField.setRows(5);
        jScrollPane2.setViewportView(instructionField);

        instructionLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        instructionLabel.setText("Instructions URL:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        menuDetailBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        menuDetailBtn.setText("More Menu Detail");
        menuDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDetailBtnActionPerformed(evt);
            }
        });

        weeklyBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        weeklyBtn.setText("Weekly Menu");
        weeklyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyBtnActionPerformed(evt);
            }
        });

        logOutBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setToolTipText("");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        repsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        repsLabel.setText("Reps:");

        repsField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(461, 461, 461)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                        .addComponent(instructionLabel)
                                        .addComponent(jScrollPane3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(repsLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(repsField))))
                                .addComponent(menuDetailBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logOutBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weeklyBtn)))
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(361, 361, 361))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dailyMenuLabel)
                        .addGap(450, 450, 450))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(dailyMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repsLabel)
                            .addComponent(repsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instructionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(menuDetailBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 868, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeklyBtn)
                    .addComponent(logOutBtn))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weeklyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyBtnActionPerformed
        this.setVisible(false);
        weeklyMenuWin.setVisible(true);
    }//GEN-LAST:event_weeklyBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        this.setVisible(false);
        logInWin.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void menuDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDetailBtnActionPerformed
        // Test
        this.displayMenu();
    }//GEN-LAST:event_menuDetailBtnActionPerformed

    public void displayMenu() {
        Calendar calendar = Calendar.getInstance();       
        int day = calendar.get(Calendar.DAY_OF_WEEK);               
        
        /*
        if (day == 1) then show Sunday's menu              
        if (day == 2) then show Monday's menu
        if (day == 3) then show Tuesday's menu
        if (day == 4) then show Wednesday's menu
        if (day == 5) then show Thursday's menu
        if (day == 6) then show Friday's menu
        if (day == 7) then show Saturday's menu
        */
        
        // instructionField.setText(weeklyMenu.get(0).get(?).getDesc());
        // repsField.setText(weeklyMenu.get(0).get(?).getReps());
        // urlField.setText(weeklyMenu.get(0).get(?).getLink());
    }
    
    public void setWeeklyMenu(ArrayList<ArrayList<WorkoutMenuItem>> weeklyMenu){
        this.weeklyMenu = weeklyMenu;
    }
        
    // Connect Each Window
    public void setWeeklyMenuWindow(WeeklyMenuWindow weeklyMenuWin) {
        this.weeklyMenuWin = weeklyMenuWin;
    }           
    public void setLogInWindow(LogInWindow logInWin) {
        this.logInWin =  logInWin;
    }         
    public void setUserMenuWindow(UserInformationWindow userInfoWin) {
        this.userInfoWin = userInfoWin;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dailyMenuLabel;
    private javax.swing.JList<String> dailyMenuList;
    private javax.swing.JTextArea instructionField;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton menuDetailBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField repsField;
    private javax.swing.JLabel repsLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton weeklyBtn;
    // End of variables declaration//GEN-END:variables
}
